---
title: "ADAC Testnoten"
format: 
  html:
    self-contained: true
editor: visual
---

## Projektziele

1. Erstellung einer Datendokumentation: Variablendefinitionen
2. Prüfung der Validität und Bereinigung dieses automatisch erstellten Datensatzes:  
  Muster der fehlenden Werte analysieren, unplausible Einträge entfernen, etc.
3. Uni- und multivariate deskriptive Analysen des Datensatzes:  
  Auswahl relevanter/interessanter Variablen und Darstellung ihrer Verteilungen und Zusammenhänge  
  (z.B. zeitliche Entwicklung umwelt- oder sicherheitstechnischer Aspekte - gerne auch eigene Ideen entwickeln)
4. Herausarbeiten interessanter/relevanter Assoziationen zwischen (Kombinationen von) Fahrzeugeigenschaften und der ADAC-Testnote:  
  Welche Fahrzeugeigenschaften stehen in besonders starkem Zusammenhang mit der ADAC-Testnote?  
  Welche anderen Faktoren modifizieren diese Zusammenhänge?

## Daten

- Quelle: Webscraping der ADAC-Testseiten (z.B. [VW Golf Variant 2.0 TDI](https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/golf/viii/315172/))
- Vollergebung der in Deutschland zugelassenen und vom ADAC getesteten Automodelle
- ca. $200 000$ Fahrzeugmodelle mit $>300$ Fahrzeugeigenschaften

## Ansprechpartner

Prof. Mathias Bühler (`mathias.buehler@econ.lmu.de`)
